version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - ${DICTIONARY_DB_PORT}:5432
    volumes:
      - ~/apps/dictionary_web_api/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DICTIONARY_DB_PASSWORD}
      - POSTGRES_USER=${DICTIONARY_DB_USER}
      - POSTGRES_DB=${DICTIONARY_DB_NAME}