version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    healthcheck:
      # check that postgres database is ready to receive connection requests
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 2
    
    ports:
      - ${DICTIONARY_DB_PORT}:5432
    volumes:
      - ~/apps/dictionary_web_api_cloned/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DICTIONARY_DB_PASSWORD}
      - POSTGRES_USER=${DICTIONARY_DB_USER}
      - POSTGRES_DB=${DICTIONARY_DB_NAME}